CREATE SEQUENCE IF NOT EXISTS User_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE "User"
(
    id    BIGINT       NOT NULL,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);